### ISSUE TITLE
Usage without Rails

### ISSUE THREAD

**Issue by scalp42** [wunderlist/reliable#5]
@nathan-ms I'm trying to use the gem:

``` ruby
require 'reliable'
require 'awesome_print'

ENV['REDIS_URL'] = 'redis://localhost:6379/0'

Reliable[:messages].push(JSON.generate({
  id: 123,
  title: "Hello"
}))

# assuming reliable:queues:messages gets created ?

Reliable[:messages].each do |message|
  puts %|Got #{message}|
end
```

Unfortunately getting:

```
redis.rb:6:in `<main>': undefined method `[]' for Reliable:Module (NoMethodError)
```

Any idea ?

**Comment by scalp42** [comment]
@nathan-ms any chance you could try in irb?

**Comment by scalp42** [comment]
So the  issue is that the project was renamed to `reliable-queue` but was never pushed to Rubygems, see https://github.com/wunderlist/reliable/commit/a6fe2347e8f3f623eda8eb3bcf95d17309deb452

Any chance you could push a release?

**Comment by scalp42** [comment]
I pushed https://rubygems.org/gems/reliable-queue to fix the issue.

**Comment by ghost** [comment]
@scalp42 sorry I didn't get back to you. The gem isn't 100% finished, so it was never pushed. We are not using this gem any longer and haven't been updating it.

Are you using it in production?
