### ISSUE TITLE
Get exceptions

### ISSUE THREAD

**Issue by scalp42** [wunderlist/reliable#6]
Looking at https://github.com/wunderlist/reliable/blob/master/lib/reliable/worker.rb#L36-L39, if something goes wrong, any exception will be swallowed and moving to next item in queue.

Is there any way to actually get back the exception somehow ? If I `raise e` in `notify` method it'll break the loop, so I'm not sure how to go about it.

**Comment by scalp42** [comment]
Hooking up into logger could be a solution but I can't figure how to override `Reliable.logger`.

**Comment by ghost** [comment]
This `rescue` is if something goes wrong in the gem code. The `process` method has it's own `rescue` which will `throw :failed` which does the main exception handling.

About the `logger`, you can simply assign it to whatever you want: https://github.com/wunderlist/reliable/blob/master/lib/reliable.rb#L30-L32

**Comment by scalp42** [comment]
@nathan-ms I'm still confused how you can get the exception `e` from https://github.com/wunderlist/reliable/blob/master/lib/reliable/worker.rb#L46

I understand it's meant to be robust but how do you actually print the exception during the loop processing?
